---
- name: stop gluster_exporter container
  community.docker.docker_container:
    name: gluster_exporter
    state: stopped
  ignore_errors: true

- name: remove gluster_exporter container
  community.docker.docker_container:
    name: gluster_exporter
    state: absent
  ignore_errors: true
