---
- name: Stop gluster_exporter container
  become: true
  ignore_errors: true
  community.docker.docker_container:
    name: gluster_exporter
    state: stopped

- name: Remove gluster_exporter container
  become: true
  ignore_errors: true
  community.docker.docker_container:
    name: gluster_exporter
    state: absent
